[tool.poetry]
name = "django-credentials"
version = "0.1.0"
description = ""
authors = ["Chris Muthig <camuthig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.0"
cryptography = "^2.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
