[tool.poetry]
name = "django-credentials"
version = "0.1.0"
description = ""
authors = ["Chris Muthig <camuthig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.0"
cryptography = "^2.9"
python-dotenv = "^0.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.770"
django-stubs = "^1.5.0"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
