[tool.poetry]
name = "env-credentials"
version = "0.1.0"
description = "A library to maintain and use encrypted .env files."
license = "MIT"
authors = ["Chris Muthig <camuthig@gmail.com>"]
readme = 'README.md'
repository = 'https://github.com/camuthig/python-env-credentials'
documentation = 'https://github.com/camuthig/python-env-credentials'
keywords = [
    "dotenv",
    "credentials",
    "encrypted",
    "settings",
    "environment variables",
    "env",
]
packages = [
    { include = "env_credentials" },
    { include = "django_credentials" }
]

[tool.poetry.dependencies]
python = "^3.7"
cryptography = "^36"
python-dotenv = "^0.13"
django = {version = "^3.0", optional = true}

#[tool.poetry.dev-dependencies]
django-stubs = {version = "^1.5.0", optional = true}
flake8 = {version = "^3.7.9", optional = true}
mypy = {version = "^0.770", optional = true}
pytest = {version = "^6.2.5", optional = true}
tox = {version = "^3.6.14", optional = true}
codecov = {version = "^2.0.22", optional = true}
pytest-cov = {version = "^2.8.1", optional = true}
coverage = {version = "^5.1", optional = true, extras = ["dev"]}

[tool.poetry.extras]

django = ["django"]
dev = ["codecov", "django-stubs", "flake8", "mypy", "pytest", "pytest-cov", "tox"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
